# Generated by Django 5.0.7 on 2025-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
