# Generated by Django 5.0.7 on 2025-02-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_ni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
