# Generated by Django 5.0.7 on 2025-02-12 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltycustomer',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_customer', to='app_admin.customer'),
        ),
    ]
