# Generated by Django 5.0.7 on 2025-02-12 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_alter_loyaltycustomer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltycustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
