# Generated by Django 5.0.7 on 2025-02-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_order_products_alter_order_transaction_id'),
        ('app_admin', '0004_order_products'),
    ]

    operations = [
    ]
