# Generated by Django 5.0.7 on 2025-01-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_alter_category_options_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app_home/static/app_home/assets/img/product_images/'),
        ),
    ]
