# Generated by Django 5.0.7 on 2025-01-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_ni',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
