# Generated by Django 5.0.7 on 2025-01-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0009_product_size_ni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='default_product_id', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.CharField(default='default_provider', max_length=200),
        ),
    ]
