# Generated by Django 5.0.7 on 2025-01-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0010_remove_product_provider_id_product_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
