# Generated by Django 5.0.7 on 2025-01-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
