# Generated by Django 5.0.7 on 2025-01-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0014_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='default_product_id', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
