# Generated by Django 5.0.7 on 2025-01-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0015_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
