# Generated by Django 5.0.7 on 2025-01-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0016_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
